GET http://localhost:3000/courses
###
GET http://localhost:3000/courses/1
###
POST http://localhost:3000/courses/
Content-Type: application/json

{
  "name": "Course NestJS",
  "description": "Course NestJS",
  "price": 50
}

###
PATCH http://localhost:3000/courses/1
Content-Type: application/json

{
  "name": "Course NestJS",
  "description": "Course NestJS",
  "price": 50
}

###
DELETE http://localhost:3000/courses/1
Content-Type: application/json

{
  "name": "Course NestJS",
  "description": "Course NestJS",
  "price": 50
}